### ISSUE TITLE
Directive does not handle colspan of the tiles

### ISSUE THREAD

**Issue by jaradehr1** [freemanlam/ng-mat-responsive-grid-list#20]
Say you have a mat-list with cols = 4

There are special cases that I don't believe it's handled in your directive..
1- If [colspan] attribute was applied on the mat-tile - ex: 
```
<mat-grid-list cols="4" rowHeight="90px" gutterSize="10px">
   <mat-grid-tile [colspan]="3"><input/></mat-grid-tile>
   <mat-grid-tile><input/></mat-grid-tile>
</mat-grid-list>
```

2- If [colspan] attribute was applied on the mat-tile and one or more or mat-tiles are actually empty (used for spacing/separating elements within the row) - ex:
```
<mat-grid-list cols="4" rowHeight="90px" gutterSize="10px">
   <mat-grid-tile [colspan]="2"><input/></mat-grid-tile>
   <mat-grid-tile></mat-grid-tile>
   <mat-grid-tile><input/></mat-grid-tile>
</mat-grid-list>
```

**Comment by jaradehr1** [comment]
Also, in your ngOnDestory()
this line `this.breakPointObserverSubscription = undefined;`
should be replaced with this line `this.breakPointObserverSubscription = Subscription.EMPTY;`

I am guessing that was allowed in previous angular versions?

**Comment by freemanlam** [comment]
Hello, sorry for late, your finding is good!  I am currently quite busy in my work, but I'll very welcome for a pull request :D

**Comment by freemanlam** [comment]
> Also, in your ngOnDestory()
> this line `this.breakPointObserverSubscription = undefined;`
> should be replaced with this line `this.breakPointObserverSubscription = Subscription.EMPTY;`
> 
> I am guessing that was allowed in previous angular versions?

Yes you're right, the previous version of this project is based on very old Angular 6. And I just restructure the project and now based on Angular 11 with strict mode, hopefully you can enjoy the new version!

Latest release: https://github.com/freemanlam/ng-mat-responsive-grid-list/releases/tag/0.0.5

**Comment by jaradehr1** [comment]
I'm saying it's a good a lib and it is worth maintaining, Cheers!

**Comment by freemanlam** [comment]
Enjoy!
